apiVersion: v1
kind: Pod

metadata:
  name: webapp-release-0 #important name, use something representative
  labels: #labels will be used to be selected by services.
    app: webapp
    release: "0"

spec:
  containers:
  - name: webapp #not really important for us, just the container name
    image: richardchesterwood/k8s-fleetman-webapp-angular:release0

# definition separator
--- 

apiVersion: v1
kind: Pod

metadata:
  name: webapp-release0-5 #important name, use something representative
  labels: #labels will be used to be selected by services.
    app: webapp
    release: "0-5"

spec:
  containers:
  - name: webapp #not really important for us, just the container name
    image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5

--- 

apiVersion: v1
kind: Pod

metadata:
  name: queue 
  labels: 
    app: queue

spec:
  containers:
  - name: queue
    image: richardchesterwood/k8s-fleetman-queue:release1