apiVersion: apps/v1
kind: ReplicaSet

metadata:
  name: webapp

spec:

  selector: #uses it to decide witch pod definition will be selected (template)
    matchLabels:
      app: webapp
  
  replicas: 1
  
  template: # a template for the pod

    metadata:
      labels: #labels will be used to be selected by services.
        app: webapp

    spec:
      containers:
      - name: webapp
        image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5

# definition separator
--- 

apiVersion: v1
kind: Pod

metadata:
  name: queue 
  labels: 
    app: queue

spec:
  containers:
  - name: queue
    image: richardchesterwood/k8s-fleetman-queue:release1