apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp # very important name we will user to handle the service

spec:
  
  selector:
    app: webapp
    release: "0-5"

  ports:
    - name : http
      port : 80 #service port. Also pod port when targetPort not defined
      nodePort: 30080 #port expose by NodePort to external use

  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue

spec:
  
  selector:
    app: queue

  ports:
    - name : http
      port : 8161
      nodePort: 30010

  type: NodePort